/**
 * Re-vendors the two fonts GRID uses.
 *
 * They are vendored rather than linked from Google Fonts so the renderer never
 * touches the network: the CSP can stay strict, cold start has no round trip,
 * and the app works offline. Both are SIL Open Font License 1.1, which
 * explicitly allows bundling with an application.
 *
 *   npm run fonts
 *
 * Only the latin and latin-ext subsets are kept, and only the variable files —
 * one file per family covers every weight the interface uses.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const OUT_CSS = path.join(here, '..', 'src', 'renderer', 'src', 'styles', 'fonts.css')
const OUT_DIR = path.join(here, '..', 'src', 'renderer', 'src', 'styles', 'fonts')

// A modern UA is required or the API serves ttf instead of woff2. The `..`
// ranges are what make Google return the variable font rather than one static
// instance per weight — ask for `wght@400;700` and you get the same file twice.
const API =
  'https://fonts.googleapis.com/css2' +
  '?family=Space+Grotesk:wght@300..700' +
  '&family=JetBrains+Mono:wght@100..800' +
  '&display=swap'

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36'

const HEADER = `/*
 * Vendored Google Fonts, SIL Open Font License 1.1.
 * Space Grotesk (c) Florian Karsten. JetBrains Mono (c) JetBrains s.r.o.
 *
 * Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 * Variable files, latin + latin-ext subsets.
 */

`

const res = await fetch(API, { headers: { 'User-Agent': UA } })
if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`)
const css = await res.text()

// Google emits a `/* subset */` comment before each @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]

fs.mkdirSync(OUT_DIR, { recursive: true })
let out = HEADER
let kept = 0

for (const [, subset, block] of blocks) {
  if (subset !== 'latin' && subset !== 'latin-ext') continue

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const weight = /font-weight:\s*([\d ]+);/.exec(block)?.[1]?.trim()
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1]
  const range = /unicode-range:\s*([^;]+)/.exec(block)?.[1]?.trim()
  if (!family || !weight || !url || !range) continue

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-var-${subset}.woff2`
  const bin = await fetch(url)
  if (!bin.ok) throw new Error(`${file}: ${bin.status}`)
  const buf = Buffer.from(await bin.arrayBuffer())
  fs.writeFileSync(path.join(OUT_DIR, file), buf)
  console.log(`${file}  ${weight}  ${buf.length} bytes`)
  kept += 1

  out +=
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${weight};\n` +
    // `block` rather than `swap`: a terminal reflowing mid-boot looks broken.
    `  font-display: block;\n` +
    `  src: url(./fonts/${file}) format('woff2-variations'), url(./fonts/${file}) format('woff2');\n` +
    `  unicode-range: ${range};\n` +
    `}\n\n`
}

if (kept === 0) throw new Error('no font faces matched — the API response shape changed')

fs.writeFileSync(OUT_CSS, out)
console.log(`\nwrote ${OUT_CSS} (${kept} faces)`)
